In [1]:
import tensorflow as tf
from tensorflow.contrib import rnn
import os,re
import numpy as np
import pandas as pd

In [2]:
test_data = pd.read_csv("test.csv")
print(len(test_data))
test_data.head(10)

1701


handle                                              tweet
0   none  Couldn't be more proud of @HillaryClinton. Her...
1   none  This election is too important to sit out. Go ...
2   none  Once again, we will have a government of, by a...
3   none  On National #VoterRegistrationDay, make sure y...
4   none  Great afternoon in Little Havana with Hispanic...
5   none  It's #NationalVoterRegistrationDay. Celebrate ...
6   none  "I love this country.\nI’m proud of this count...
7   none  "What kind of a person would want to root for ...
8   none  "I don’t think that any family should have to ...
9   none  Join Hillary live in NC for her first rally si...

In [3]:
train_data = pd.read_csv("train.csv",header = None)
print(len(train_data))
train_data.describe()
train_data[0].head(10)

4743


0    The question in this election: Who can put the...
1    Last night, Donald Trump said not paying taxes...
2    If we stand together, there's nothing we can't...
3    Both candidates were asked about how they'd co...
4    Join me for a 3pm rally - tomorrow at the Mid-...
5    When Donald Trump goes low...register to vote:...
6    3) Has Trump offered a single proposal to redu...
7    The election is just weeks away. Check if you'...
8    Hillary Clinton's Campaign Continues To Make F...
9    'CNBC, Time magazine online polls say Donald T...
Name: 0, dtype: object

In [4]:
text = train_data[0].copy()
test_text = test_data['tweet'].copy()
labels_train = pd.read_csv("labels_train_tweets.csv",header = None)
labels_train[0] = labels_train[0].map({'HC':1,'DT':0})
test_text.head()
#Hillary = 1 , DT = 0

0    Couldn't be more proud of @HillaryClinton. Her...
1    This election is too important to sit out. Go ...
2    Once again, we will have a government of, by a...
3    On National #VoterRegistrationDay, make sure y...
4    Great afternoon in Little Havana with Hispanic...
Name: tweet, dtype: object

In [5]:
labels_train.head(10)

0
0  1
1  1
2  1
3  1
4  0
5  1
6  1
7  1
8  0
9  0

In [6]:
from keras import backend as K
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

Using TensorFlow backend.


In [7]:
#The actual vocab size was around 12k, but using a larger number 
#reduces the probability of collisions from the hash function.
vocab_size = 10 #000
encoded_tweets = [one_hot(d, vocab_size) for d in train_data[0]]
encoded_test = [one_hot(d, vocab_size) for d in test_text]
tweet_lengths = [len(t) for t in encoded_tweets]
test_lengths = [len(t) for t in encoded_test]
max_length = 0
for t in encoded_tweets:
    if len(t) > max_length:
        max_length = len(t)
        
for t in encoded_test:
    if len(t) > max_length:
        max_length = len(t)

labels_train
padded_tweets
tweet_lengths

In [8]:
class SimpleDataIterator():
    def __init__(self, df):
        self.df = df
        self.size = len(self.df)
        self.epochs = 0
        self.shuffle()

    def shuffle(self):
        self.df = self.df.sample(frac=1).reset_index(drop=True)
        self.cursor = 0

    def next_batch(self, n):
        if self.cursor+n-1 > self.size:
            self.epochs += 1
            self.shuffle()
        res = self.df.ix[self.cursor:self.cursor+n-1]
        self.cursor += n
        return res['data'], res['labels'], res['length']

In [9]:
train_dic={}
train_dic["data"] = encoded_tweets
train_dic["labels"] = labels_train[0].ravel().tolist()
train_dic["length"] = tweet_lengths
train_len = len(train_data)
test_len = len(test_data)

train = pd.DataFrame.from_dict(data=train_dic, orient='columns', dtype=None)


test_dic={}
test_dic["data"] = encoded_test
test_dic["length"] = test_lengths
test = pd.DataFrame.from_dict(data=test_dic, orient='columns', dtype=None)

test_input = test.values

data = SimpleDataIterator(train)
d = data.next_batch(3)
print('Input sequences\n', d[0], end='\n\n')
print('Target values\n', d[1], end='\n\n')
print('Sequence lengths\n', d[2])

Input sequences
 0    [2, 7, 3, 1, 3, 2, 4, 5, 9, 9, 2, 6, 1, 1, 7, ...
1                                   [1, 9, 6, 9, 6, 6]
2    [3, 3, 2, 1, 9, 4, 2, 5, 5, 1, 5, 4, 9, 8, 4, ...
Name: data, dtype: object

Target values
 0    1
1    1
2    0
Name: labels, dtype: int64

Sequence lengths
 0    21
1     6
2    19
Name: length, dtype: int64


/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:16: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  app.launch_new_instance()


In [10]:
class PaddedDataIterator(SimpleDataIterator):
    def next_batch(self, n):
        if self.cursor+n > self.size:
            self.epochs += 1
            self.shuffle()
        res = self.df.ix[self.cursor:self.cursor+n-1]
        self.cursor += n

        # Pad sequences with 0s so they are all the same length
        maxlen = max(res['length'])
        x = np.zeros([n, maxlen], dtype=np.int32)
        for i, x_i in enumerate(x):
            x_i[:res['length'].values[i]] = res['data'].values[i]

        return x, res['labels'], res['length']

In [38]:
data = PaddedDataIterator(train)
train_data = PaddedDataIterator(test)
d = data.next_batch(3)
print('Input sequences\n', d[0], end='\n\n')

Input sequences
 [[3 3 7 8 5 3 8 3 9 9 8 9 8 9 9 1 5 7 4 3 2 2]
 [8 3 5 3 9 1 1 4 4 9 8 9 1 1 9 3 3 9 4 3 2 5]
 [9 3 5 5 7 3 3 8 7 8 4 3 2 8 0 0 0 0 0 0 0 0]]



/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


In [25]:
def reset_graph():
    if 'sess' in globals() and sess:
        sess.close()
    tf.reset_default_graph()

def build_graph(
    vocab_size = vocab_size,
    state_size = 24,
    batch_size = 189,
    num_classes = 2):

    reset_graph()

    # Placeholders
    x = tf.placeholder(tf.int32, [batch_size, None]) # [batch_size, num_steps]
    seqlen = tf.placeholder(tf.int32, [batch_size])
    y = tf.placeholder(tf.int32, [batch_size])
    keep_prob = tf.placeholder_with_default(1.0, [])

    # Embedding layer
    embeddings = tf.get_variable('embedding_matrix', [vocab_size, state_size])
    rnn_inputs = tf.nn.embedding_lookup(embeddings, x)

    # RNN
    cell = tf.nn.rnn_cell.BasicLSTMCell(state_size,forget_bias = 1)
    #cell = tf.contrib.rnn.LSTMCell(state_size,forget_bias = 1)
    init_state = tf.get_variable('init_state', [1, state_size],
                                 initializer=tf.constant_initializer(0.0))
    init_state = tf.tile(init_state, [batch_size, 1])
    rnn_outputs, final_state = tf.nn.dynamic_rnn(cell, rnn_inputs,dtype=tf.float32)#, sequence_length=seqlen,initial_state=init_state)

    # Add dropout, as the model otherwise quickly overfits
    rnn_outputs = tf.nn.dropout(rnn_outputs, keep_prob)

    """
    Obtain the last relevant output. The best approach in the future will be to use:

        last_rnn_output = tf.gather_nd(rnn_outputs, tf.pack([tf.range(batch_size), seqlen-1], axis=1))

    which is the Tensorflow equivalent of numpy's rnn_outputs[range(30), seqlen-1, :], but the
    gradient for this op has not been implemented as of this writing.

    The below solution works, but throws a UserWarning re: the gradient.
    """
    idx = tf.range(batch_size)*tf.shape(rnn_outputs)[1] + (seqlen - 1)
    last_rnn_output = tf.gather(tf.reshape(rnn_outputs, [-1, state_size]), idx)

    # Softmax layer
    with tf.variable_scope('softmax'):
        W = tf.get_variable('W', [state_size, num_classes])
        b = tf.get_variable('b', [num_classes], initializer=tf.constant_initializer(0.0))
    logits = tf.matmul(last_rnn_output, W) + b
    preds = tf.nn.softmax(logits)
    correct = tf.equal(tf.cast(tf.argmax(preds,1),tf.int32), y)
    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

    loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits = logits, labels = y))
    train_step = tf.train.AdamOptimizer(1e-4).minimize(loss)

    return {
        'x': x,
        'seqlen': seqlen,
        'y': y,
        'dropout': keep_prob,
        'loss': loss,
        'ts': train_step,
        'preds': preds,
        'accuracy': accuracy
    }

def train_graph(graph, sess, batch_size = 189, num_epochs = 30000, iterator = PaddedDataIterator):
    
    
    sess.run(tf.global_variables_initializer())
    tr = iterator(train)
    te = iterator(test)

    step, accuracy = 0, 0
    tr_losses, te_losses = [], []
    current_epoch = 0
    while current_epoch < num_epochs:
        step += 1
        batch = tr.next_batch(batch_size)
        feed = {g['x']: batch[0], g['y']: batch[1], g['seqlen']: batch[2], g['dropout']: 0.6}
        accuracy_, _ = sess.run([g['accuracy'], g['ts']], feed_dict=feed)
        accuracy += accuracy_

        if tr.epochs > current_epoch:
            current_epoch += 1
            tr_losses.append(accuracy / step)
            step, accuracy = 0, 0
            if step >1 and accuracy/step >= 0.98:
                break;
            #eval test set
            """ te_epoch = te.epochs
            while te.epochs == te_epoch:
                step += 1
                batch = te.next_batch(batch_size)
                feed = {g['x']: batch[0], g['y']: batch[1], g['seqlen']: batch[2]}
                accuracy_ = sess.run([g['accuracy'],g['loss']], feed_dict=feed)[0]
                accuracy += accuracy_

            te_losses.append(accuracy / step)"""
            step, accuracy = 0,0
            if current_epoch%100 == 0:
                print("Accuracy after epoch", current_epoch, " - tr:", tr_losses[-1])#, "- te:", te_losses[-1])
    return tr_losses#, te_losses

In [ ]:
g = build_graph()
#tr_losses, te_losses = train_graph(g)
sess = tf.Session()
tr_losses = train_graph(g, sess)

/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


Accuracy after epoch 100  - tr: 0.695026450157
Accuracy after epoch 200  - tr: 0.70497354269
Accuracy after epoch 300  - tr: 0.718518507481
Accuracy after epoch 400  - tr: 0.729100530148
Accuracy after epoch 500  - tr: 0.732275128365
Accuracy after epoch 600  - tr: 0.742857139111
Accuracy after epoch 700  - tr: 0.746666657925
Accuracy after epoch 800  - tr: 0.743280417919
Accuracy after epoch 900  - tr: 0.753862428665
Accuracy after epoch 1000  - tr: 0.758518507481
Accuracy after epoch 1100  - tr: 0.766772484779
Accuracy after epoch 1200  - tr: 0.761693117619
Accuracy after epoch 1300  - tr: 0.772910044193
Accuracy after epoch 1400  - tr: 0.77777777195
Accuracy after epoch 1500  - tr: 0.776296288967
Accuracy after epoch 1600  - tr: 0.772063493729
Accuracy after epoch 1700  - tr: 0.771216924191
Accuracy after epoch 1800  - tr: 0.782222218513
Accuracy after epoch 1900  - tr: 0.78730158329
Accuracy after epoch 2000  - tr: 0.791111104488
Accuracy after epoch 2100  - tr: 0.78962962389
Accur

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
x = [x for x in range(len(tr_losses))]
plt.figure(figsize=(20,15))
plt.plot(x,tr_losses, label = "Training Step vs Training Accuracy")
plt.xlabel("epoch")
plt.ylabel("Training Accuracy")
plt.legend()
plt.savefig("best_LSTM.png")
plt.show()


In [ ]:
test_input = test
test_input['data'] = test['data'].apply(lambda x : np.array(x))
test_input['length'] = test_input['length'].apply(lambda x : np.array(x))
maxlen = max(test_input['length'])
x = np.zeros([len(test_input), maxlen], dtype=np.int32)
for i, x_i in enumerate(x):
    x_i[:test_input['length'].values[i]] = test_input['data'].values[i]

results = []
import math
for i in range(math.floor(len(x)/189)):
    data_bit = x[i*189:(i+1)*189]
    len_bit = test_input['length'][i*189:(i+1)*189]
    results.append(sess.run([g["preds"]], feed_dict={g['x']: data_bit, g['seqlen'] : len_bit}))
print(results[0])


In [ ]:
print(results[0][0][32])


In [ ]:

with open("output_LSTM.txt", "w") as f:
    f.write("id,realDonaldTrump,HillaryClinton\n")
    #batch of 189
    i = 0
    print (len(results))
    for n in range(len(results)):
        print (len(results[n][0]))
        for y in range(len(results[n][0])):
            f.write("{},{:06f},{:06f}\n".format(i, results[n][0][y][0],results[n][0][y][1]))
            i = i+1
    